name: global_repository
description: A new Flutter package project.
version: 0.0.1
# homepage:
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.0
  synchronized: ^3.0.0
  flutter_markdown: ^0.7.4+3
  get: ^4.1.3
  # launcher url

  responsive_framework: ^1.0.0
  signale: ^0.0.10
  # 提供路径访问
  permission_handler: ^11.3.1
  window_manager: ^0.3.0
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master
  dio: ^5.4.3+1
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  assets:
    - assets/icon/
#dependency_overrides:
#  url_launcher: ^6.0.18
# signale:
#   path: ../signale
